_Michael_Tinnin/Models/Wage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _Michael_Tinnin.Models
{
    public class Wage
    {
        public string Name { get; set; }
        public int EmployeeNumber { get; set; }
        public Decimal Hours { get; set; }
        public Decimal Rate { get; set; }
        public String Wage_
        {
            get
            {
                decimal wage = 0;

                if (Hours <= 40)
                {
                    wage = Hours * Rate;
                }
                else
                {
                    decimal overtimeHours = 0;
                    overtimeHours = Hours - 40;

                    wage = (overtimeHours * (1.5M * Rate)) + 40 * Rate;
                }

                return wage.ToString("C");
            }
        }




        public Wage()
        {
            Name = "Michael Tinnin";
            EmployeeNumber = 123456;
            Hours = 40;
            Rate = 10;
            

        }

    }
}

_Michael_Tinnin/Models/WageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _Michael_Tinnin.Models
{
    public class WageViewModel
    {
        public Wage Wage { get; set; }

        public WageViewModel()
        {
            Wage = new Wage();
        }
    }
}

_Michael_Tinnin/Controllers/WageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _Michael_Tinnin.Models;

namespace _Michael_Tinnin.Controllers
{
    public class WageController : Controller
    {
        // GET: Wage
        public ActionResult Index()
        {
            WageViewModel model = new WageViewModel();
            return View(model);
            
        }
        [HttpPost]
        public ActionResult Index(WageViewModel model)
        {
            return View(model);
        }
    }
}

_Michael_Tinnin/Views/Wage/Index.cshtml
@model _Michael_Tinnin.Models.WageViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Wage Calculator</h2>

@using (Html.BeginForm("Index", "Wage", new { Area = "" }, FormMethod.Post, new { id = "WageForm" }))
{
    <table>
        <tr>
            <td>
                Employee Number:
            </td>
            <td>
                @Html.TextBoxFor(m => m.Wage.EmployeeNumber)
            </td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>
                @Html.TextBoxFor(m => m.Wage.Name)
            </td>
        </tr>
        <tr>
            <td>Hours Worked:</td>
            <td>
                @Html.TextBoxFor(m => m.Wage.Hours)
            </td>
        </tr>
        <tr>
            <td>Hourly Rate:</td>
            <td>
                @Html.TextBoxFor(m => m.Wage.Rate)
            </td>
        </tr>
        <tr>
            <td>Wage:</td>
            <td>
                @Html.Raw(Model.Wage.Wage_)
            </td>
        </tr>

    </table>
    <input type="submit" value="Calculate"> 
    
}